"""Explicit enumerations for every PACT protocol concept.

No boolean ``success`` flags are used anywhere in the protocol: each lifecycle is
represented by an explicit state from one of these enums.
"""

from __future__ import annotations

from enum import StrEnum


class TransactionState(StrEnum):
    CREATED = "CREATED"
    SPECIFYING = "SPECIFYING"
    PREPARING = "PREPARING"
    PREPARED = "PREPARED"
    COMMITTING = "COMMITTING"
    VERIFYING = "VERIFYING"
    COMMITTED_VERIFIED = "COMMITTED_VERIFIED"
    ABORTING = "ABORTING"
    ABORTED = "ABORTED"
    UNKNOWN = "UNKNOWN"
    RECONCILING = "RECONCILING"
    COMPENSATING = "COMPENSATING"
    COMPENSATED = "COMPENSATED"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    FAILED_TERMINAL = "FAILED_TERMINAL"


class EffectState(StrEnum):
    PROPOSED = "PROPOSED"
    VALIDATED = "VALIDATED"
    PREPARED = "PREPARED"
    DISPATCHING = "DISPATCHING"
    DISPATCHED = "DISPATCHED"
    VERIFYING = "VERIFYING"
    VERIFIED = "VERIFIED"
    UNKNOWN = "UNKNOWN"
    RECONCILING = "RECONCILING"
    RETRYABLE = "RETRYABLE"
    FAILED = "FAILED"
    COMPENSATING = "COMPENSATING"
    COMPENSATED = "COMPENSATED"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"
    # Never dispatched; released because the transaction aborted or entered
    # recovery before this effect crossed into execution (see ADR-0004).
    ABORTED = "ABORTED"


class ReversibilityClass(StrEnum):
    REVERSIBLE = "REVERSIBLE"
    COMPENSABLE = "COMPENSABLE"
    IRREVERSIBLE = "IRREVERSIBLE"
    EXTERNALLY_REVERSIBLE = "EXTERNALLY_REVERSIBLE"
    UNKNOWN_REVERSIBILITY = "UNKNOWN_REVERSIBILITY"


class ClaimMode(StrEnum):
    READ = "READ"
    WRITE = "WRITE"
    EXCLUSIVE = "EXCLUSIVE"


class InvariantPhase(StrEnum):
    PREPARE = "PREPARE"
    PRE_COMMIT = "PRE_COMMIT"
    POST_EXECUTION = "POST_EXECUTION"
    FINAL = "FINAL"


class FailureAction(StrEnum):
    BLOCK_PREPARE = "BLOCK_PREPARE"
    BLOCK_COMMIT = "BLOCK_COMMIT"
    ABORT = "ABORT"
    RECONCILE = "RECONCILE"
    COMPENSATE = "COMPENSATE"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"


class Severity(StrEnum):
    CRITICAL = "CRITICAL"
    ERROR = "ERROR"
    WARNING = "WARNING"


class PrepareStrategy(StrEnum):
    READ_PRECONDITIONS = "READ_PRECONDITIONS"
    NONE = "NONE"


class CommitStrategy(StrEnum):
    SINGLE_DISPATCH = "SINGLE_DISPATCH"


class VerificationStrategy(StrEnum):
    QUERY_BY_IDEMPOTENCY_KEY = "QUERY_BY_IDEMPOTENCY_KEY"
    QUERY_TARGET_STATE = "QUERY_TARGET_STATE"


class CompensationStrategy(StrEnum):
    NONE = "NONE"
    INVERSE_OPERATION = "INVERSE_OPERATION"
    RESTORE_BEFORE_IMAGE = "RESTORE_BEFORE_IMAGE"


class IdempotencyStrategy(StrEnum):
    PROVIDER_IDEMPOTENCY_KEY = "PROVIDER_IDEMPOTENCY_KEY"
    TARGET_STATE_IDEMPOTENT = "TARGET_STATE_IDEMPOTENT"


class ReconciliationPolicy(StrEnum):
    """How an UNKNOWN effect may be resolved.

    QUERY_BY_IDEMPOTENCY_KEY: the provider can authoritatively answer whether an
    operation with this key exists, so "not found" is SAFE_TO_RETRY.
    QUERY_TARGET_STATE: the provider exposes the target state; reaching it means
    applied, otherwise safe to retry because the operation is state-idempotent.
    MANUAL: no authoritative read path; UNKNOWN escalates to a human.
    """

    QUERY_BY_IDEMPOTENCY_KEY = "QUERY_BY_IDEMPOTENCY_KEY"
    QUERY_TARGET_STATE = "QUERY_TARGET_STATE"
    MANUAL = "MANUAL"


class DispatchOutcome(StrEnum):
    """Immediate classification of an external call - richer than success/fail."""

    ACCEPTED = "ACCEPTED"  # provider returned success (TOOL_CALL_SUCCEEDED, not verified)
    REJECTED_DEFINITIVE = "REJECTED_DEFINITIVE"  # provider refused; not applied
    REJECTED_RETRYABLE = "REJECTED_RETRYABLE"  # provider declined before applying (e.g. 503)
    RESPONSE_LOST = "RESPONSE_LOST"  # request may have been applied; outcome unknown
    NOT_SENT = "NOT_SENT"  # transport failure before the request left PACT


class VerificationStatus(StrEnum):
    VERIFIED_SUCCESS = "VERIFIED_SUCCESS"
    VERIFIED_FAILURE = "VERIFIED_FAILURE"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    VERIFICATION_UNKNOWN = "VERIFICATION_UNKNOWN"


class ProviderFinding(StrEnum):
    """What an adapter observed when reconciling against external state."""

    APPLIED = "APPLIED"
    NOT_APPLIED = "NOT_APPLIED"
    INDETERMINATE = "INDETERMINATE"
    CONFLICTING = "CONFLICTING"


class ReconciliationOutcome(StrEnum):
    VERIFIED_SUCCESS = "VERIFIED_SUCCESS"
    SAFE_TO_RETRY = "SAFE_TO_RETRY"
    STILL_UNKNOWN = "STILL_UNKNOWN"
    HUMAN_REQUIRED = "HUMAN_REQUIRED"


class LogicalOperationStatus(StrEnum):
    AVAILABLE = "AVAILABLE"
    RESERVED = "RESERVED"
    IN_FLIGHT = "IN_FLIGHT"
    UNKNOWN = "UNKNOWN"
    VERIFIED = "VERIFIED"
    RETRYABLE = "RETRYABLE"
    FAILED = "FAILED"
    COMPENSATED = "COMPENSATED"


class AttemptKind(StrEnum):
    EXECUTE = "EXECUTE"
    COMPENSATE = "COMPENSATE"
    RECONCILE = "RECONCILE"


class AttemptStatus(StrEnum):
    INTENT_RECORDED = "INTENT_RECORDED"
    ACCEPTED = "ACCEPTED"
    REJECTED_DEFINITIVE = "REJECTED_DEFINITIVE"
    REJECTED_RETRYABLE = "REJECTED_RETRYABLE"
    RESPONSE_LOST = "RESPONSE_LOST"
    NOT_SENT = "NOT_SENT"
    ABANDONED_BY_RESTART = "ABANDONED_BY_RESTART"
    FOUND_APPLIED = "FOUND_APPLIED"
    FOUND_NOT_APPLIED = "FOUND_NOT_APPLIED"
    INDETERMINATE = "INDETERMINATE"
    CONFLICTING = "CONFLICTING"


class OperatorActionType(StrEnum):
    APPROVE = "APPROVE"
    RETRY_RECONCILIATION = "RETRY_RECONCILIATION"
    RETRY_COMPENSATION = "RETRY_COMPENSATION"
    MARK_EFFECT_COMPENSATED = "MARK_EFFECT_COMPENSATED"
    FINALIZE_FAILED = "FINALIZE_FAILED"


class EventType(StrEnum):
    TRANSACTION_CREATED = "TRANSACTION_CREATED"
    CHILD_TRANSACTION_CREATED = "CHILD_TRANSACTION_CREATED"
    CAPABILITY_ISSUED = "CAPABILITY_ISSUED"
    CAPABILITY_DELEGATED = "CAPABILITY_DELEGATED"
    CAPABILITY_DELEGATION_REJECTED = "CAPABILITY_DELEGATION_REJECTED"
    INVARIANT_REGISTERED = "INVARIANT_REGISTERED"
    TRANSACTION_STATE_CHANGED = "TRANSACTION_STATE_CHANGED"
    EFFECT_PROPOSED = "EFFECT_PROPOSED"
    EFFECT_VALIDATED = "EFFECT_VALIDATED"
    EFFECT_STATE_CHANGED = "EFFECT_STATE_CHANGED"
    EFFECT_PREPARED = "EFFECT_PREPARED"
    EFFECT_PREPARE_FAILED = "EFFECT_PREPARE_FAILED"
    AUTHORITY_EVALUATED = "AUTHORITY_EVALUATED"
    CONFLICT_DETECTED = "CONFLICT_DETECTED"
    INVARIANT_EVALUATED = "INVARIANT_EVALUATED"
    COMMIT_BARRIER_EVALUATED = "COMMIT_BARRIER_EVALUATED"
    LOGICAL_OPERATIONS_RESERVED = "LOGICAL_OPERATIONS_RESERVED"
    EXECUTION_SCHEDULE_EVALUATED = "EXECUTION_SCHEDULE_EVALUATED"
    EFFECT_DISPATCH_STARTED = "EFFECT_DISPATCH_STARTED"
    EFFECT_DISPATCHED = "EFFECT_DISPATCHED"
    EFFECT_DISPATCH_REJECTED = "EFFECT_DISPATCH_REJECTED"
    EFFECT_DISPATCH_RETRYABLE = "EFFECT_DISPATCH_RETRYABLE"
    EFFECT_DISPATCH_UNKNOWN = "EFFECT_DISPATCH_UNKNOWN"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_PENDING = "VERIFICATION_PENDING"
    EFFECT_VERIFIED = "EFFECT_VERIFIED"
    EFFECT_VERIFICATION_FAILED = "EFFECT_VERIFICATION_FAILED"
    EFFECT_VERIFICATION_UNKNOWN = "EFFECT_VERIFICATION_UNKNOWN"
    RECONCILIATION_STARTED = "RECONCILIATION_STARTED"
    RECONCILIATION_RESOLVED = "RECONCILIATION_RESOLVED"
    RECONCILIATION_FINISHED = "RECONCILIATION_FINISHED"
    RECOVERY_DECISION = "RECOVERY_DECISION"
    EFFECT_RELEASED = "EFFECT_RELEASED"
    COMPENSATION_STARTED = "COMPENSATION_STARTED"
    EFFECT_COMPENSATION_STARTED = "EFFECT_COMPENSATION_STARTED"
    EFFECT_COMPENSATED = "EFFECT_COMPENSATED"
    EFFECT_COMPENSATION_FAILED = "EFFECT_COMPENSATION_FAILED"
    COMPENSATION_NOT_POSSIBLE = "COMPENSATION_NOT_POSSIBLE"
    COMPENSATION_FINISHED = "COMPENSATION_FINISHED"
    FINAL_VERIFICATION_STARTED = "FINAL_VERIFICATION_STARTED"
    FINAL_VERIFICATION_FINISHED = "FINAL_VERIFICATION_FINISHED"
    OPERATOR_ACTION_RECORDED = "OPERATOR_ACTION_RECORDED"
    RESTART_RECOVERY = "RESTART_RECOVERY"
    TRANSACTION_FINALIZED = "TRANSACTION_FINALIZED"
    RECEIPT_CREATED = "RECEIPT_CREATED"
    QUARANTINED_LEGACY = "QUARANTINED_LEGACY"
    RECEIPT_AMENDED = "RECEIPT_AMENDED"
    TRANSACTION_ABORT_REQUESTED = "TRANSACTION_ABORT_REQUESTED"
    EFFECT_WITHDRAWN = "EFFECT_WITHDRAWN"
    RECOVERY_DEADLINE_EXCEEDED = "RECOVERY_DEADLINE_EXCEEDED"
    STALE_WORKER_FENCED = "STALE_WORKER_FENCED"
    WORK_TAKEN_OVER = "WORK_TAKEN_OVER"
    WORK_ENQUEUED = "WORK_ENQUEUED"
    RESIDUAL_RESOLVED = "RESIDUAL_RESOLVED"
    RESIDUAL_RECORDED = "RESIDUAL_RECORDED"
    OBSERVATION_RECORDED = "OBSERVATION_RECORDED"
    BUDGET_CONSUMED = "BUDGET_CONSUMED"
    BUDGET_HELD = "BUDGET_HELD"
    RESERVATIONS_RELEASED = "RESERVATIONS_RELEASED"
    RESERVATIONS_TAKEN = "RESERVATIONS_TAKEN"
    COMMIT_REQUESTED = "COMMIT_REQUESTED"
    APPROVAL_RECORDED = "APPROVAL_RECORDED"
    PLAN_REVISED = "PLAN_REVISED"
    PLAN_NEEDS_CLARIFICATION = "PLAN_NEEDS_CLARIFICATION"
    PLAN_REJECTED = "PLAN_REJECTED"
    PLAN_FROZEN = "PLAN_FROZEN"


# =========================================================================== Phase 2
# Outcome truth: three independent dimensions recorded per effect and per observation.


class Application(StrEnum):
    """What PACT knows about whether the external operation took effect."""

    NOT_SENT = "NOT_SENT"  # never left PACT
    NOT_APPLIED_CONFIRMED = "NOT_APPLIED_CONFIRMED"  # authoritative evidence it was not applied
    APPLIED = "APPLIED"  # evidence the provider applied it (correctly or not)
    UNKNOWN = "UNKNOWN"  # may or may not have been applied


class Postcondition(StrEnum):
    """Does the observed external state match the declared expected outcome?"""

    MATCH = "MATCH"
    MISMATCH = "MISMATCH"
    PARTIAL = "PARTIAL"
    UNDETERMINED = "UNDETERMINED"


class Restoration(StrEnum):
    NOT_REQUIRED = "NOT_REQUIRED"  # nothing applied, or restoration not requested
    PENDING = "PENDING"  # restoration required and not yet attempted / in progress
    RESTORED = "RESTORED"  # restoration verified against external state
    PARTIAL = "PARTIAL"
    RESIDUAL = "RESIDUAL"  # cannot be restored (irreversible, stale, or failed definitively)
    UNKNOWN = "UNKNOWN"  # restoration attempt outcome unknown
    HUMAN_ATTESTED = "HUMAN_ATTESTED"  # an operator attests restoration; not provider-verified


class Consistency(StrEnum):
    STRONG = "STRONG"
    EVENTUAL = "EVENTUAL"


class ObservationPurpose(StrEnum):
    PREPARE = "PREPARE"
    FRESHNESS = "FRESHNESS"
    VERIFY = "VERIFY"
    RECONCILE = "RECONCILE"
    FINAL = "FINAL"
    COMPENSATION_VERIFY = "COMPENSATION_VERIFY"
    LATE_RESPONSE = "LATE_RESPONSE"


class ResidualKind(StrEnum):
    APPLIED_MISMATCH = "APPLIED_MISMATCH"
    UNKNOWN_OUTCOME = "UNKNOWN_OUTCOME"
    IRREVERSIBLE_CONSEQUENCE = "IRREVERSIBLE_CONSEQUENCE"
    COMPENSATION_FAILED = "COMPENSATION_FAILED"
    COMPENSATION_UNKNOWN = "COMPENSATION_UNKNOWN"
    STALE_RESTORATION_BLOCKED = "STALE_RESTORATION_BLOCKED"
    RETAINED_HISTORY = "RETAINED_HISTORY"


class ResidualDisposition(StrEnum):
    OPEN = "OPEN"
    RESOLVED = "RESOLVED"  # resolved by external evidence
    ATTESTED = "ATTESTED"  # an operator attests resolution (not provider-verified)
    ACCEPTED = "ACCEPTED"  # policy accepts it (e.g. retained audit history)


class PlanRevisionStatus(StrEnum):
    DRAFT = "DRAFT"
    NEEDS_CLARIFICATION = "NEEDS_CLARIFICATION"
    REJECTED = "REJECTED"
    FROZEN = "FROZEN"
    SUPERSEDED = "SUPERSEDED"
    EXECUTING = "EXECUTING"


class PrincipalKind(StrEnum):
    AGENT = "AGENT"
    OPERATOR = "OPERATOR"
    SERVICE = "SERVICE"


class WorkKind(StrEnum):
    PREPARE = "PREPARE"
    DRIVE = "DRIVE"  # all post-barrier progress: execute, verify, reconcile, compensate, finalize


class WorkStatus(StrEnum):
    READY = "READY"
    CLAIMED = "CLAIMED"
    DONE = "DONE"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ReservationStatus(StrEnum):
    ACTIVE = "ACTIVE"
    RELEASED = "RELEASED"
    RETAINED = "RETAINED"  # kept because an unresolved/irreversible consequence remains


class BudgetEntryKind(StrEnum):
    HOLD = "HOLD"
    RELEASE_HOLD = "RELEASE_HOLD"
    CONSUME = "CONSUME"


class CommitRequestStatus(StrEnum):
    QUEUED = "QUEUED"
    BLOCKED = "BLOCKED"
    AWAITING_APPROVAL = "AWAITING_APPROVAL"
