"""initial pact schema

Includes database-enforced guarantees: append-only transaction_events,
immutable receipts, and CHECK constraints restricting state columns to the
protocol enums.

Revision ID: 0001
Revises: 
Create Date: 2026-10-02 21:56:00.426768
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from app.domain.enums import EffectState, TransactionState

revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logical_operations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('operation_key', sa.String(length=512), nullable=False),
    sa.Column('effect_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('owner_root_id', sa.Uuid(), nullable=True),
    sa.Column('owner_effect_id', sa.Uuid(), nullable=True),
    sa.Column('provider_idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('provider_reference', sa.String(length=256), nullable=True),
    sa.Column('verified_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('operation_key')
    )
    op.create_table('transaction_events',
    sa.Column('sequence', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('sequence'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_events_root_seq', 'transaction_events', ['root_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_transaction_events_transaction_id'), 'transaction_events', ['transaction_id'], unique=False)
    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('capability_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_parent_id'), 'transactions', ['parent_id'], unique=False)
    op.create_index(op.f('ix_transactions_root_id'), 'transactions', ['root_id'], unique=False)
    op.create_index(op.f('ix_transactions_state'), 'transactions', ['state'], unique=False)
    op.create_table('capabilities',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('parent_capability_id', sa.Uuid(), nullable=True),
    sa.Column('subject_id', sa.String(length=128), nullable=False),
    sa.Column('issuer', sa.String(length=128), nullable=False),
    sa.Column('scope', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('cumulative_limit', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delegation_depth', sa.Integer(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['parent_capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_transaction_id'), 'capabilities', ['transaction_id'], unique=False)
    op.create_table('commit_decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('snapshot_version', sa.Integer(), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('blocking_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commit_decisions_transaction_id'), 'commit_decisions', ['transaction_id'], unique=False)
    op.create_table('effects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('logical_operation_id', sa.Uuid(), nullable=False),
    sa.Column('operation_key', sa.String(length=512), nullable=False),
    sa.Column('contract_type', sa.String(length=128), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('state', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('resource_claims', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('depends_on', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reversibility_class', sa.String(length=32), nullable=False),
    sa.Column('provider_idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('provider_reference', sa.String(length=256), nullable=True),
    sa.Column('prepare_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dispatch_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verification_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reconciliation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('compensation_result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['logical_operation_id'], ['logical_operations.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_effects_logical_operation_id'), 'effects', ['logical_operation_id'], unique=False)
    op.create_index(op.f('ix_effects_operation_key'), 'effects', ['operation_key'], unique=False)
    op.create_index(op.f('ix_effects_root_id'), 'effects', ['root_id'], unique=False)
    op.create_index(op.f('ix_effects_transaction_id'), 'effects', ['transaction_id'], unique=False)
    op.create_table('invariants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('expression_type', sa.String(length=64), nullable=False),
    sa.Column('definition', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('failure_action', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id', 'key')
    )
    op.create_index(op.f('ix_invariants_transaction_id'), 'invariants', ['transaction_id'], unique=False)
    op.create_table('operator_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=True),
    sa.Column('operator_id', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operator_actions_transaction_id'), 'operator_actions', ['transaction_id'], unique=False)
    op.create_table('receipts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('receipt_version', sa.String(length=32), nullable=False),
    sa.Column('final_state', sa.String(length=32), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_index(op.f('ix_receipts_root_id'), 'receipts', ['root_id'], unique=False)
    op.create_table('effect_dependencies',
    sa.Column('from_effect_id', sa.Uuid(), nullable=False),
    sa.Column('to_effect_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_effect_id'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['to_effect_id'], ['effects.id'], ),
    sa.PrimaryKeyConstraint('from_effect_id', 'to_effect_id')
    )
    op.create_table('invariant_evaluations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('invariant_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('context', sa.String(length=64), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('observed_values', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invariant_id'], ['invariants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invariant_evaluations_invariant_id'), 'invariant_evaluations', ['invariant_id'], unique=False)
    op.create_index(op.f('ix_invariant_evaluations_transaction_id'), 'invariant_evaluations', ['transaction_id'], unique=False)
    op.create_table('operation_attempts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('logical_operation_id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('request', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['logical_operation_id'], ['logical_operations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('logical_operation_id', 'kind', 'attempt_no')
    )
    op.create_index(op.f('ix_operation_attempts_logical_operation_id'), 'operation_attempts', ['logical_operation_id'], unique=False)
    # ### end Alembic commands ###
    _forbid_mutation("transaction_events", "transaction_events is append-only")
    _forbid_mutation("receipts", "receipts are immutable once finalized")
    op.create_check_constraint("ck_transactions_state", "transactions", _in("state", TransactionState))
    op.create_check_constraint("ck_effects_state", "effects", _in("state", EffectState))


def _in(column: str, enum) -> str:
    return f"{column} IN ({', '.join(repr(m.value) for m in enum)})"


def _forbid_mutation(table: str, message: str) -> None:
    op.execute(f"""
        CREATE OR REPLACE FUNCTION pact_forbid_{table}_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '{message}' USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute(f"""
        CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table}
        FOR EACH ROW EXECUTE FUNCTION pact_forbid_{table}_mutation();
    """)


def downgrade() -> None:
    for table in ("receipts", "transaction_events"):
        op.execute(f"DROP TRIGGER IF EXISTS trg_{table}_immutable ON {table}")
        op.execute(f"DROP FUNCTION IF EXISTS pact_forbid_{table}_mutation()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operation_attempts_logical_operation_id'), table_name='operation_attempts')
    op.drop_table('operation_attempts')
    op.drop_index(op.f('ix_invariant_evaluations_transaction_id'), table_name='invariant_evaluations')
    op.drop_index(op.f('ix_invariant_evaluations_invariant_id'), table_name='invariant_evaluations')
    op.drop_table('invariant_evaluations')
    op.drop_table('effect_dependencies')
    op.drop_index(op.f('ix_receipts_root_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_operator_actions_transaction_id'), table_name='operator_actions')
    op.drop_table('operator_actions')
    op.drop_index(op.f('ix_invariants_transaction_id'), table_name='invariants')
    op.drop_table('invariants')
    op.drop_index(op.f('ix_effects_transaction_id'), table_name='effects')
    op.drop_index(op.f('ix_effects_root_id'), table_name='effects')
    op.drop_index(op.f('ix_effects_operation_key'), table_name='effects')
    op.drop_index(op.f('ix_effects_logical_operation_id'), table_name='effects')
    op.drop_table('effects')
    op.drop_index(op.f('ix_commit_decisions_transaction_id'), table_name='commit_decisions')
    op.drop_table('commit_decisions')
    op.drop_index(op.f('ix_capabilities_transaction_id'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_index(op.f('ix_transactions_state'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_root_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_parent_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_transaction_events_transaction_id'), table_name='transaction_events')
    op.drop_index('ix_events_root_seq', table_name='transaction_events')
    op.drop_table('transaction_events')
    op.drop_table('logical_operations')
    # ### end Alembic commands ###
