"""phase2 trust, ownership, outcome truth

Additive. Existing Phase 1 evidence is preserved. Legacy rows are backfilled
conservatively (unknown outcomes are never recorded as "not applied"), and
non-terminal legacy transactions are QUARANTINED from automatic execution
because they lack Phase 2 safety metadata (workflow policy, frozen digest,
reservations). See docs/phase2/architecture.md, "Migration".

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-03 22:04:43.402533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0002'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=128), nullable=False),
    sa.Column('route', sa.String(length=256), nullable=False),
    sa.Column('body_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'principal_id', 'request_id')
    )
    op.create_table('budget_scopes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_table('observations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=False),
    sa.Column('attempt_id', sa.Uuid(), nullable=True),
    sa.Column('purpose', sa.String(length=32), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('provenance', sa.String(length=16), nullable=False),
    sa.Column('provider_reference', sa.String(length=256), nullable=True),
    sa.Column('consistency', sa.String(length=16), nullable=False),
    sa.Column('application', sa.String(length=32), nullable=False),
    sa.Column('postcondition', sa.String(length=32), nullable=False),
    sa.Column('restoration', sa.String(length=32), nullable=True),
    sa.Column('negative_authoritative', sa.Boolean(), nullable=False),
    sa.Column('authoritative', sa.Boolean(), nullable=False),
    sa.Column('observed_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_digest', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_observations_effect_id'), 'observations', ['effect_id'], unique=False)
    op.create_index(op.f('ix_observations_root_id'), 'observations', ['root_id'], unique=False)
    op.create_table('proposal_traces',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=256), nullable=True),
    sa.Column('live', sa.Boolean(), nullable=False),
    sa.Column('request_id', sa.String(length=256), nullable=True),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('schema_version', sa.String(length=32), nullable=False),
    sa.Column('intent_digest', sa.String(length=64), nullable=False),
    sa.Column('proposal', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('validation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=True),
    sa.Column('latency_ms', sa.Numeric(precision=12, scale=1), nullable=True),
    sa.Column('usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('residual_obligations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('bound_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('required_remediation', sa.Text(), nullable=False),
    sa.Column('blocking', sa.Boolean(), nullable=False),
    sa.Column('disposition', sa.String(length=16), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('evidence_observation_id', sa.Uuid(), nullable=True),
    sa.Column('resolution', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_residual_obligations_effect_id'), 'residual_obligations', ['effect_id'], unique=False)
    op.create_index(op.f('ix_residual_obligations_root_id'), 'residual_obligations', ['root_id'], unique=False)
    op.create_table('resources',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'key')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('scope_id', sa.Uuid(), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scope_id'], ['budget_scopes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_entries_effect_id'), 'budget_entries', ['effect_id'], unique=False)
    op.create_index(op.f('ix_budget_entries_root_id'), 'budget_entries', ['root_id'], unique=False)
    op.create_index(op.f('ix_budget_entries_scope_id'), 'budget_entries', ['scope_id'], unique=False)
    op.create_table('plan_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('workflow', sa.String(length=64), nullable=False),
    sa.Column('workflow_version', sa.String(length=16), nullable=False),
    sa.Column('policy_version', sa.String(length=32), nullable=False),
    sa.Column('compiled', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('digest', sa.String(length=64), nullable=True),
    sa.Column('compile_result', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('frozen_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['root_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_id', 'revision_no')
    )
    op.create_index(op.f('ix_plan_revisions_root_id'), 'plan_revisions', ['root_id'], unique=False)
    op.create_table('principals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('grants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_principals_tenant_id'), 'principals', ['tenant_id'], unique=False)
    op.create_table('work_items',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('owner', sa.String(length=128), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('epoch', sa.Integer(), nullable=False),
    sa.Column('runs', sa.Integer(), nullable=False),
    sa.Column('max_runs', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['root_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_items_root_id'), 'work_items', ['root_id'], unique=False)
    op.create_index(op.f('ix_work_items_status'), 'work_items', ['status'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('revision_id', sa.Uuid(), nullable=False),
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('approver_principal_id', sa.Uuid(), nullable=False),
    sa.Column('approver_name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approver_principal_id'], ['principals.id'], ),
    sa.ForeignKeyConstraint(['revision_id'], ['plan_revisions.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approvals_root_id'), 'approvals', ['root_id'], unique=False)
    op.create_table('credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('lookup', sa.String(length=64), nullable=False),
    sa.Column('verifier', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credentials_lookup'), 'credentials', ['lookup'], unique=False)
    op.create_index(op.f('ix_credentials_principal_id'), 'credentials', ['principal_id'], unique=False)
    op.create_table('receipt_amendments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('receipt_id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('previous_hash', sa.String(length=64), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_amendments_receipt_id'), 'receipt_amendments', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipt_amendments_transaction_id'), 'receipt_amendments', ['transaction_id'], unique=False)
    op.create_table('reservations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('resource_key', sa.String(length=512), nullable=False),
    sa.Column('root_id', sa.Uuid(), nullable=False),
    sa.Column('effect_id', sa.Uuid(), nullable=False),
    sa.Column('mode', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('released_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['effect_id'], ['effects.id'], ),
    sa.ForeignKeyConstraint(['resource_id'], ['resources.id'], ),
    sa.ForeignKeyConstraint(['root_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_reservations_active', 'reservations', ['tenant_id', 'resource_key', 'status'], unique=False)
    op.create_index(op.f('ix_reservations_root_id'), 'reservations', ['root_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('principal_id', sa.Uuid(), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_id'], ['principals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('effects', sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='demo'))
    op.add_column('effects', sa.Column('client_operation_key', sa.String(length=512), nullable=True))
    op.add_column('effects', sa.Column('slot', sa.String(length=64), nullable=True))
    op.add_column('effects', sa.Column('contract_id', sa.String(length=128), nullable=True))
    op.add_column('effects', sa.Column('contract_version', sa.String(length=32), nullable=True))
    op.add_column('effects', sa.Column('contract_hash', sa.String(length=64), nullable=True))
    op.add_column('effects', sa.Column('application', sa.String(length=32), nullable=False, server_default='NOT_SENT'))
    op.add_column('effects', sa.Column('postcondition', sa.String(length=32), nullable=False, server_default='UNDETERMINED'))
    op.add_column('effects', sa.Column('restoration', sa.String(length=32), nullable=False, server_default='NOT_REQUIRED'))
    op.add_column('effects', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('effects', sa.Column('observed_amount', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('effects', sa.Column('max_exposure', sa.Numeric(precision=18, scale=2), nullable=True))
    op.add_column('effects', sa.Column('payload_fingerprint', sa.String(length=64), nullable=True))
    op.add_column('effects', sa.Column('canonical_resource', sa.String(length=512), nullable=True))
    op.add_column('effects', sa.Column('revision_no', sa.Integer(), nullable=True))
    op.add_column('effects', sa.Column('legacy', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('effects', 'logical_operation_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_effects_tenant_id'), 'effects', ['tenant_id'], unique=False)
    op.add_column('logical_operations', sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='demo'))
    op.add_column('logical_operations', sa.Column('provider', sa.String(length=64), nullable=True))
    op.add_column('logical_operations', sa.Column('business_request_key', sa.String(length=512), nullable=True))
    op.add_column('logical_operations', sa.Column('slot', sa.String(length=64), nullable=True))
    op.add_column('logical_operations', sa.Column('canonical_resource', sa.String(length=512), nullable=True))
    op.add_column('logical_operations', sa.Column('epoch', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('logical_operations', sa.Column('payload_fingerprint', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_logical_operations_tenant_id'), 'logical_operations', ['tenant_id'], unique=False)
    op.add_column('operation_attempts', sa.Column('work_item_id', sa.Uuid(), nullable=True))
    op.add_column('operation_attempts', sa.Column('worker_epoch', sa.Integer(), nullable=True))
    op.add_column('operation_attempts', sa.Column('authoritative', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('transactions', sa.Column('tenant_id', sa.String(length=64), nullable=False, server_default='demo'))
    op.add_column('transactions', sa.Column('principal_id', sa.Uuid(), nullable=True))
    op.add_column('transactions', sa.Column('workflow', sa.String(length=64), nullable=True))
    op.add_column('transactions', sa.Column('workflow_version', sa.String(length=16), nullable=True))
    op.add_column('transactions', sa.Column('business_request_key', sa.String(length=512), nullable=True))
    op.add_column('transactions', sa.Column('current_revision', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('transactions', sa.Column('quarantined', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('transactions', sa.Column('quarantine_reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_transactions_business_request_key'), 'transactions', ['business_request_key'], unique=False)
    op.create_index(op.f('ix_transactions_tenant_id'), 'transactions', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
    _phase2_data_and_guards()


def downgrade() -> None:
    import os
    if os.environ.get('PACT_ALLOW_LOSSY_DOWNGRADE') != '1':
        raise RuntimeError('Downgrading 0002 drops Phase 2 evidence (observations, residuals, approvals, '
                           'reservations). Back up first and set PACT_ALLOW_LOSSY_DOWNGRADE=1 to proceed.')
    for t in ('observations', 'budget_entries', 'receipt_amendments'):
        op.execute(f'DROP TRIGGER IF EXISTS trg_{t}_immutable ON {t}')
        op.execute(f'DROP FUNCTION IF EXISTS pact_forbid_{t}_mutation()')
    op.execute('DROP INDEX IF EXISTS ux_work_items_one_active_per_root')
    for c in ('ck_effects_application', 'ck_effects_postcondition', 'ck_effects_restoration'):
        op.execute(f'ALTER TABLE effects DROP CONSTRAINT IF EXISTS {c}')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_tenant_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_business_request_key'), table_name='transactions')
    op.drop_column('transactions', 'quarantine_reason')
    op.drop_column('transactions', 'quarantined')
    op.drop_column('transactions', 'current_revision')
    op.drop_column('transactions', 'business_request_key')
    op.drop_column('transactions', 'workflow_version')
    op.drop_column('transactions', 'workflow')
    op.drop_column('transactions', 'principal_id')
    op.drop_column('transactions', 'tenant_id')
    op.drop_column('operation_attempts', 'authoritative')
    op.drop_column('operation_attempts', 'worker_epoch')
    op.drop_column('operation_attempts', 'work_item_id')
    op.drop_index(op.f('ix_logical_operations_tenant_id'), table_name='logical_operations')
    op.drop_column('logical_operations', 'payload_fingerprint')
    op.drop_column('logical_operations', 'epoch')
    op.drop_column('logical_operations', 'canonical_resource')
    op.drop_column('logical_operations', 'slot')
    op.drop_column('logical_operations', 'business_request_key')
    op.drop_column('logical_operations', 'provider')
    op.drop_column('logical_operations', 'tenant_id')
    op.drop_index(op.f('ix_effects_tenant_id'), table_name='effects')
    op.alter_column('effects', 'logical_operation_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('effects', 'legacy')
    op.drop_column('effects', 'revision_no')
    op.drop_column('effects', 'canonical_resource')
    op.drop_column('effects', 'payload_fingerprint')
    op.drop_column('effects', 'max_exposure')
    op.drop_column('effects', 'observed_amount')
    op.drop_column('effects', 'currency')
    op.drop_column('effects', 'restoration')
    op.drop_column('effects', 'postcondition')
    op.drop_column('effects', 'application')
    op.drop_column('effects', 'contract_hash')
    op.drop_column('effects', 'contract_version')
    op.drop_column('effects', 'contract_id')
    op.drop_column('effects', 'slot')
    op.drop_column('effects', 'client_operation_key')
    op.drop_column('effects', 'tenant_id')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_reservations_root_id'), table_name='reservations')
    op.drop_index('ix_reservations_active', table_name='reservations')
    op.drop_table('reservations')
    op.drop_index(op.f('ix_receipt_amendments_transaction_id'), table_name='receipt_amendments')
    op.drop_index(op.f('ix_receipt_amendments_receipt_id'), table_name='receipt_amendments')
    op.drop_table('receipt_amendments')
    op.drop_index(op.f('ix_credentials_principal_id'), table_name='credentials')
    op.drop_index(op.f('ix_credentials_lookup'), table_name='credentials')
    op.drop_table('credentials')
    op.drop_index(op.f('ix_approvals_root_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_work_items_status'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_root_id'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_principals_tenant_id'), table_name='principals')
    op.drop_table('principals')
    op.drop_index(op.f('ix_plan_revisions_root_id'), table_name='plan_revisions')
    op.drop_table('plan_revisions')
    op.drop_index(op.f('ix_budget_entries_scope_id'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_root_id'), table_name='budget_entries')
    op.drop_index(op.f('ix_budget_entries_effect_id'), table_name='budget_entries')
    op.drop_table('budget_entries')
    op.drop_table('tenants')
    op.drop_table('resources')
    op.drop_index(op.f('ix_residual_obligations_root_id'), table_name='residual_obligations')
    op.drop_index(op.f('ix_residual_obligations_effect_id'), table_name='residual_obligations')
    op.drop_table('residual_obligations')
    op.drop_table('proposal_traces')
    op.drop_index(op.f('ix_observations_root_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_effect_id'), table_name='observations')
    op.drop_table('observations')
    op.drop_table('budget_scopes')
    op.drop_table('api_requests')
    # ### end Alembic commands ###


def _in(column: str, values) -> str:
    return f"{column} IN ({', '.join(repr(str(getattr(v, 'value', v))) for v in values)})"


def _append_only(table: str, message: str) -> None:
    op.execute(f"""
        CREATE OR REPLACE FUNCTION pact_forbid_{table}_mutation() RETURNS trigger AS $$
        BEGIN
            RAISE EXCEPTION '{message}' USING ERRCODE = 'integrity_constraint_violation';
        END;
        $$ LANGUAGE plpgsql;
    """)
    op.execute(f"""
        CREATE TRIGGER trg_{table}_immutable BEFORE UPDATE OR DELETE ON {table}
        FOR EACH ROW EXECUTE FUNCTION pact_forbid_{table}_mutation();
    """)


TERMINAL = ("COMMITTED_VERIFIED", "ABORTED", "COMPENSATED", "FAILED_TERMINAL")


def _phase2_data_and_guards() -> None:
    op.execute("INSERT INTO tenants (id, name, created_at) VALUES ('demo', 'Demo tenant', now()) "
               "ON CONFLICT (id) DO NOTHING")
    # At most one active (READY/CLAIMED) work item per root transaction.
    op.execute("CREATE UNIQUE INDEX ux_work_items_one_active_per_root ON work_items (root_id) "
               "WHERE status IN ('READY', 'CLAIMED')")

    # --- Legacy backfill: conservative. Unknown is never recorded as "not applied". ---
    op.execute("""
        UPDATE effects SET
          legacy = true,
          contract_id = 'legacy.' || contract_type,
          contract_version = '1.0.0',
          currency = CASE WHEN amount IS NOT NULL THEN 'USD' END,
          application = CASE
            WHEN state IN ('PROPOSED', 'VALIDATED', 'PREPARED', 'ABORTED') THEN 'NOT_SENT'
            WHEN state IN ('VERIFIED', 'COMPENSATING', 'COMPENSATED') THEN 'APPLIED'
            WHEN state = 'HUMAN_REQUIRED' AND compensation_result IS NOT NULL THEN 'APPLIED'
            WHEN state = 'FAILED' AND dispatch_result->>'outcome' = 'REJECTED_DEFINITIVE'
                 AND verification_result IS NULL THEN 'NOT_APPLIED_CONFIRMED'
            ELSE 'UNKNOWN' END,
          postcondition = CASE
            WHEN state IN ('VERIFIED', 'COMPENSATING', 'COMPENSATED') THEN 'MATCH'
            WHEN state = 'HUMAN_REQUIRED' AND compensation_result IS NOT NULL THEN 'MATCH'
            WHEN verification_result->>'status' = 'VERIFIED_FAILURE' THEN 'MISMATCH'
            ELSE 'UNDETERMINED' END,
          restoration = CASE
            WHEN state = 'COMPENSATED' THEN 'RESTORED'
            WHEN state IN ('COMPENSATING', 'HUMAN_REQUIRED') AND compensation_result IS NOT NULL THEN 'UNKNOWN'
            ELSE 'NOT_REQUIRED' END
    """)

    # --- Quarantine non-terminal legacy transactions from automatic execution. ---
    op.execute(f"""
        UPDATE transactions t SET quarantined = true,
          quarantine_reason = 'Phase 1 transaction without Phase 2 safety metadata (workflow policy, frozen '
                              || 'plan digest, reservations). Automatic execution is disabled; an operator '
                              || 'may reconcile (read-only) or finalize it.'
        WHERE EXISTS (SELECT 1 FROM transactions r WHERE r.id = t.root_id AND r.state NOT IN {TERMINAL!r})
    """)
    # Make the unresolved legacy consequences visible as residual obligations.
    op.execute(f"""
        INSERT INTO residual_obligations (id, tenant_id, root_id, effect_id, kind, description, amount, currency,
                                          required_remediation, blocking, disposition, created_at)
        SELECT gen_random_uuid(), e.tenant_id, e.root_id, e.id,
               CASE WHEN e.application = 'UNKNOWN' THEN 'UNKNOWN_OUTCOME' ELSE 'COMPENSATION_UNKNOWN' END,
               'Legacy Phase 1 effect with unresolved outcome (' || e.state || ')',
               e.amount, e.currency,
               'Operator review: reconcile against the provider or finalize with an attestation.',
               true, 'OPEN', now()
        FROM effects e JOIN transactions r ON r.id = e.root_id
        WHERE r.state NOT IN {TERMINAL!r}
          AND (e.application = 'UNKNOWN' OR e.restoration = 'UNKNOWN')
    """)

    # --- Constraints and append-only guarantees for Phase 2 evidence. ---
    from app.domain.enums import Application, Postcondition, Restoration

    op.create_check_constraint("ck_effects_application", "effects", _in("application", Application))
    op.create_check_constraint("ck_effects_postcondition", "effects", _in("postcondition", Postcondition))
    op.create_check_constraint("ck_effects_restoration", "effects", _in("restoration", Restoration))
    _append_only("observations", "observations are append-only evidence")
    _append_only("budget_entries", "budget_entries is an append-only ledger")
    _append_only("receipt_amendments", "receipt amendments are immutable")
